// Engines API — maps 20 core engines to their generated capabilities
import { NextResponse } from "next/server"
import { db } from "@/lib/db"

export const runtime = "nodejs"
export const dynamic = "force-dynamic"

export async function GET() {
  try {
    // Get real counts for each engine's capabilities
    const [memories, knowledgeChunks, conversations, messages, tasks, projects, goals, habits, skills, prompts, artifacts, auditEntries, healthScans, scheduledTasks, backlogItems, failures, checkpoints, models, providers, plugins, mcpServers, backups, reviewRequests, roles, hypotheses, metricsSnapshots] = await Promise.all([
      db.memory.count(), db.knowledgeChunk.count(), db.conversation.count(), db.message.count(),
      db.pTask.count(), db.project.count(), db.goal.count(), db.habit.count(),
      (db as any).collabSkillLibrary?.count().catch(() => 0) ?? 0,
      (db as any).collabPromptLibrary?.count().catch(() => 0) ?? 0,
      (db as any).collabSharedArtifact?.count().catch(() => 0) ?? 0,
      db.auditEntry.count().catch(() => 0), db.autonomousHealthScan.count().catch(() => 0),
      db.scheduledTask.count().catch(() => 0), db.autonomousBacklogItem.count().catch(() => 0),
      (db as any).reliabilityFailure?.count().catch(() => 0) ?? 0,
      (db as any).reliabilityCheckpoint?.count().catch(() => 0) ?? 0,
      db.modelProfile.count({ where: { active: true } }).catch(() => 0),
      db.provider.count({ where: { enabled: true } }).catch(() => 0),
      db.plugin.count().catch(() => 0),
      0, // mcpServers (in-memory)
      db.backupArchive.count().catch(() => 0),
      db.collabReviewRequest?.count().catch(() => 0) ?? 0,
      db.collabProjectRole?.count().catch(() => 0) ?? 0,
      (db as any).selfImprovementHypothesis?.count().catch(() => 0) ?? 0,
      (db as any).selfImprovementMetric?.count().catch(() => 0) ?? 0,
    ])

    const engines = [
      {
        id: 1, name: "Conversation Engine", nameAr: "محرك المحادثة",
        icon: "💬", color: "blue",
        source: "src/lib/conversation-os/",
        capabilities: ["Streaming Chat", "Multi-Model", "Branching", "Forking", "Tags", "Pins", "Export", "Search", "Summary", "Resume"],
        featureRange: "36-55",
        realData: { conversations, messages },
        realDataLabels: ["محادثات", "رسائل"],
        description: "نواة المحادثة: streaming، تعدد نماذج، تفريع، تنظيم، بحث",
      },
      {
        id: 2, name: "Agent Runtime", nameAr: "محرك الوكيل",
        icon: "🤖", color: "purple",
        source: "src/lib/agent/",
        capabilities: ["Plan Mode", "Agent Mode", "Research Mode", "Debug Mode", "Roles", "Delegation", "Teams", "Subagent Isolation"],
        featureRange: "177-190",
        realData: { conversations },
        realDataLabels: ["جلسات"],
        description: "تنفيذ المهام بأدوار متعددة: تخطيط، بحث، تصحيح، مراجعة",
      },
      {
        id: 3, name: "Model Router", nameAr: "موجّه النماذج",
        icon: "🧭", color: "cyan",
        source: "src/lib/model-intelligence/ + src/lib/cost-os/",
        capabilities: ["Capability Router", "Fast/Strong Pair", "Fallback Chain", "Provider Failover", "Warmup", "Idle Unload", "Routing Analytics"],
        featureRange: "434-444",
        realData: { models, providers },
        realDataLabels: ["نماذج", "مزودين"],
        description: "توجيه ذكي حسب نوع المهمة + failover + warmup",
      },
      {
        id: 4, name: "Tool Gateway", nameAr: "بوابة الأدوات",
        icon: "🔌", color: "orange",
        source: "src/lib/tools/ + src/lib/mcp/",
        capabilities: ["Tool Registry", "Schema", "Routing", "Permissions", "Risk Scoring", "Timeout", "Retry", "Audit", "MCP Tools"],
        featureRange: "191-217",
        realData: { plugins, skills },
        realDataLabels: ["إضافات", "skills"],
        description: "تسجيل + توجيه + صلاحيات + audit لكل أداة",
      },
      {
        id: 5, name: "Repository Intelligence", nameAr: "ذكاء المستودع",
        icon: "📁", color: "emerald",
        source: "src/lib/code-intel/",
        capabilities: ["Repo Scan", "File Index", "Symbol Index", "AST Index", "Import Graph", "Call Graph", "Hotspot Detection", "Impact Analysis"],
        featureRange: "151-176",
        realData: { healthScans },
        realDataLabels: ["فحوصات"],
        description: "Tree-sitter + LSP + AST-grep لفهم المشروع",
      },
      {
        id: 6, name: "Evidence Engine", nameAr: "محرك الأدلة",
        icon: "🔬", color: "pink",
        source: "src/lib/evaluation/",
        capabilities: ["Evidence Collection", "Test Run", "Lint", "Build", "Definition of Done", "Verification Ladder"],
        featureRange: "131-150",
        realData: { healthScans },
        realDataLabels: ["تحققات"],
        description: "تجميع أدلة قبل/أثناء/بعد التنفيذ",
      },
      {
        id: 7, name: "Context Engine", nameAr: "محرك السياق",
        icon: "🧩", color: "indigo",
        source: "src/lib/conversation-os/ (context)",
        capabilities: ["Auto Selection", "Budgeting", "Compression", "Dedup", "Paging", "Cache", "Inspector", "Relevance Score"],
        featureRange: "56-70",
        realData: { messages },
        realDataLabels: ["رسائل"],
        description: "إدارة ذكية للسياق: ضغط، ترقيم، cache",
      },
      {
        id: 8, name: "Memory Engine", nameAr: "محرك الذاكرة",
        icon: "🧠", color: "amber",
        source: "src/lib/memory/",
        capabilities: ["Working", "Session", "Task", "Project", "Personal", "Semantic", "Episodic", "Failure", "Decision", "Decay", "Consolidation", "Viewer", "Editor"],
        featureRange: "71-95",
        realData: { memories },
        realDataLabels: ["ذكريات"],
        description: "13 نوع ذاكرة: تشغيلية، جلسة، مهمة، مشروع، شخصية، دلالية، حدثية...",
      },
      {
        id: 9, name: "Knowledge Engine", nameAr: "محرك المعرفة",
        icon: "📚", color: "purple",
        source: "src/lib/knowledge/",
        capabilities: ["KB", "PDF/DOCX/PPTX/XLSX", "OCR", "Hybrid Retrieval", "Reranking", "Citations", "Knowledge Graph", "Agentic Retrieval"],
        featureRange: "96-115",
        realData: { knowledgeChunks },
        realDataLabels: ["أجزاء معرفة"],
        description: "RAG + BM25 + Vector + Reranking + Graph",
      },
      {
        id: 10, name: "Research Engine", nameAr: "محرك البحث",
        icon: "🔍", color: "blue",
        source: "src/lib/research/",
        capabilities: ["Web Search", "Multi-Query", "Source Discovery", "URL Fetch", "Ranking", "Dedup", "Claim Extraction", "Verification", "Report", "To-Knowledge"],
        featureRange: "116-130",
        realData: { knowledgeChunks },
        realDataLabels: ["نتائج بحث"],
        description: "بحث وكيلي متعدد الخطوات مع citations",
      },
      {
        id: 11, name: "Workflow Engine", nameAr: "محرك سير العمل",
        icon: "⚡", color: "orange",
        source: "src/lib/automation/",
        capabilities: ["Builder", "Scheduled Jobs", "Triggers", "Conditional Branches", "Retry", "Logs", "Templates", "Human Approval"],
        featureRange: "291-303",
        realData: { scheduledTasks },
        realDataLabels: ["مهام مجدولة"],
        description: "جدولة + triggers + شروط + موافقات بشرية",
      },
      {
        id: 12, name: "Task Engine", nameAr: "محرك المهام",
        icon: "✅", color: "emerald",
        source: "src/lib/productivity/ + src/lib/autonomous-se/",
        capabilities: ["Backlog Generation", "Dedup", "Prioritization", "Cooldown", "Supersession", "DAG", "Sequential", "Parallel"],
        featureRange: "361-370",
        realData: { tasks, backlogItems },
        realDataLabels: ["مهام", "backlog"],
        description: "توليد backlog ذكي + DAG + تنفيذ تسلسلي/متوازي",
      },
      {
        id: 13, name: "Verification Engine", nameAr: "محرك التحقق",
        icon: "🛡️", color: "red",
        source: "src/lib/security-os/ + src/lib/reliability/",
        capabilities: ["Permission Matrix", "Approval Queue", "Path Sandbox", "Command Sanitizer", "Secret Detection", "Injection Detection", "Hash-Chained Audit", "Loop Guard", "Failure Memory", "Negative Learning"],
        featureRange: "325-350",
        realData: { auditEntries, failures },
        realDataLabels: ["audit", "فشل"],
        description: "أمان + موثوقية + تعلم من الأخطاء",
      },
      {
        id: 14, name: "Security Engine", nameAr: "محرك الأمان",
        icon: "🔒", color: "red",
        source: "src/lib/security-os/",
        capabilities: ["Permission Matrix", "Approvals", "Path Traversal Protection", "Dangerous Command Detection", "Secret Redaction", "Prompt Injection Detection", "Plugin/MCP Permissions"],
        featureRange: "325-337",
        realData: { auditEntries },
        realDataLabels: ["قرارات أمان"],
        description: "صلاحيات + sandbox + كشف أسرار + حقن",
      },
      {
        id: 15, name: "MCP Engine", nameAr: "محرك MCP",
        icon: "🔗", color: "cyan",
        source: "src/lib/mcp/",
        capabilities: ["Server Manager", "Tool Discovery", "Scopes", "Health", "Auth", "Secret Management", "Rate Limiting", "Audit", "Lazy Loading"],
        featureRange: "206-217",
        realData: { plugins },
        realDataLabels: ["خوادم"],
        description: "تكامل MCP كامل: اكتشاف + صلاحيات + audit",
      },
      {
        id: 16, name: "Browser Engine", nameAr: "محرك المتصفح",
        icon: "🌐", color: "blue",
        source: "src/lib/browser/ (Playwright)",
        capabilities: ["Launch", "Navigate", "DOM", "Click", "Fill", "Screenshot", "Console", "Network", "Session", "Profiles"],
        featureRange: "218-230",
        realData: { artifacts },
        realDataLabels: ["screenshots"],
        description: "Playwright: تصفح + تفاعل + فحص + screenshots",
      },
      {
        id: 17, name: "Project Engine", nameAr: "محرك المشاريع",
        icon: "🏗️", color: "amber",
        source: "src/lib/productivity/ + src/lib/dev-experience/",
        capabilities: ["Project Switcher", "Templates", "Scaffolding", "Framework Detection", "Constitution", "Critical Files", "DoD Templates", "Runbooks"],
        featureRange: "393-405",
        realData: { projects },
        realDataLabels: ["مشاريع"],
        description: "قوالب + كشف + دستور + ملفات محمية",
      },
      {
        id: 18, name: "Session Engine", nameAr: "محرك الجلسات",
        icon: "🔄", color: "purple",
        source: "src/lib/backup-recovery/ + src/lib/observability/",
        capabilities: ["Resume", "Checkpoint", "Crash Recovery", "Replay", "Backup", "Timeline", "Recovery Wizard"],
        featureRange: "426-433",
        realData: { checkpoints, backups },
        realDataLabels: ["نقاط حفظ", "نسخ احتياطية"],
        description: "استعادة + checkpoint + crash recovery + replay",
      },
      {
        id: 19, name: "Observability Engine", nameAr: "محرك المراقبة",
        icon: "📊", color: "teal",
        source: "src/lib/observability/ + src/lib/self-improvement/",
        capabilities: ["Agent Timeline", "Tool Timeline", "Token Analytics", "Latency (p50/p95/p99)", "RAM/CPU", "Failure Dashboard", "Bottleneck Detection", "A/B Testing", "Hypotheses", "Promotion"],
        featureRange: "371-392",
        realData: { metricsSnapshots, hypotheses },
        realDataLabels: ["لقطات", "فرضيات"],
        description: "مراقبة + تحليلات + تحسين ذاتي",
      },
      {
        id: 20, name: "Resource/Hardware Engine", nameAr: "محرك الموارد",
        icon: "⚙️", color: "orange",
        source: "src/lib/resource-intelligence/ + src/lib/cost-os/",
        capabilities: ["Adaptive Threads", "Adaptive Context", "RAM Pressure", "VRAM Pressure", "Process Manager", "Idle Killer", "Throttling", "Indexing Scheduler", "Pressure Modes (GREEN/YELLOW/ORANGE/RED)"],
        featureRange: "445-453",
        realData: { scheduledTasks },
        realDataLabels: ["مهام مجدولة"],
        description: "تكيّف ديناميكي حسب RAM/CPU/VRAM",
      },
    ]

    const totalCapabilities = engines.reduce((s, e) => s + e.capabilities.length, 0)

    return NextResponse.json({
      engines,
      totalEngines: engines.length,
      totalCapabilities,
      totalFeatures: 484,
      ratio: `${engines.length} محركات → ${totalCapabilities} قدرات → 484 ميزة`,
      message: "عدد قليل من المحركات القوية يُنتج مئات الاستخدامات — لا 484 نظاماً منفصلاً",
    })
  } catch (e) {
    return NextResponse.json({ error: String(e) }, { status: 500 })
  }
}
